flat_bonjour.Rmd:
  path: dev/flat_bonjour.Rmd
  state: active
  R: R/dire_bonjour.R
  tests: tests/testthat/test-dire_bonjour.R
  vignettes: vignettes/minimal.Rmd
  inflate:
    flat_file: dev/flat_bonjour.Rmd
    vignette_name: Minimal
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
