---
title: "flat_bonjour.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
library(testthat)
```

# dire_bonjour

```{r development-bonjour}
# Prepare the code of your function here
library(glue)
prenom <- "Vincent"
glue("Bonjour {prenom} !")
```

```{r function-bonjour}

#' Dire Bonjour
#'
#' @param prenom character : Name of the person to greet. Default is "toi".
#'
#' @returns character : A greeting message.
#' @details This function takes a name as input and returns a greeting message in the format "Bonjour \{prenom\} !". If no name is provided, it defaults to "toi".
#' @importFrom glue glue
#' 
#' @export
#'
#' @examples
dire_bonjour <- function(prenom = "toi") {
  texte <- glue("Bonjour {prenom}")
  return(texte)
}
```

```{r examples-bonjour}
dire_bonjour(prenom = "Vincent")
dire_bonjour()
```

```{r tests-bonjour}
test_that("bonjour works", {
  expect_true(inherits(dire_bonjour, "function"))
  expect_equal(dire_bonjour("Vincent"), "Bonjour Vincent")
  expect_equal(dire_bonjour(), "Bonjour toi")
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_bonjour.Rmd", vignette_name = "Minimal")
```
