# WARNING - Generated by {fusen} from dev/flat_bonjour.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("bonjour works", {
  expect_true(inherits(dire_bonjour, "function"))
  expect_equal(dire_bonjour("Vincent"), "Bonjour, Vincent")
  expect_equal(dire_bonjour(), "Bonjour, toi")
})
